## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-switch-os-path-workflow

# base domain
domain: com.tumblr.ramiroaraujo

name: Switch OS Path
description: Switch back and forth between UNIX filepaths and Windows filepaths, based on previous mapping configuration between Volume names and Network Drive names
created_by: Ramiro Araujo
website: https://github.com/ramiroaraujo/alfred-switch-os-path-workflow
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox